from django.urls import path

from . import views


urlpatterns = [
    path(
        "publishing/submissions/<uuid:submission_id>/create-draft/",
        views.CreateArticleDraftView.as_view(),
        name="publishing-create-draft",
    ),
    path(
        "publishing/issues/",
        views.IssueManagementListCreateView.as_view(),
        name="publishing-issue-list",
    ),
    path(
        "publishing/issues/<uuid:issue_id>/",
        views.IssueManagementDetailView.as_view(),
        name="publishing-issue-detail",
    ),
    path(
        "publishing/issues/<uuid:issue_id>/open/",
        views.OpenIssueView.as_view(),
        name="publishing-issue-open",
    ),
    path(
        "publishing/issues/<uuid:issue_id>/close/",
        views.CloseIssueView.as_view(),
        name="publishing-issue-close",
    ),
    path(
        "publishing/articles/",
        views.ArticleManagementListView.as_view(),
        name="publishing-article-list",
    ),
    path(
        "publishing/articles/<uuid:article_id>/",
        views.ArticleManagementDetailView.as_view(),
        name="publishing-article-detail",
    ),
    path(
        "publishing/articles/<uuid:article_id>/publish/",
        views.PublishArticleView.as_view(),
        name="publishing-article-publish",
    ),
    path(
        "public/journal/",
        views.PublicJournalView.as_view(),
        name="public-journal",
    ),

        path(
        "public/pages/<slug:slug>/",
        views.PublicJournalContentPageView.as_view(),
        name="public-journal-content-page",
    ),
    
    path(
        "public/sections/",
        views.PublicSectionListView.as_view(),
        name="public-section-list",
    ),
    path(
        "public/sections/<uuid:section_id>/articles/",
        views.PublicSectionArticleListView.as_view(),
        name="public-section-article-list",
    ),
    path(
        "public/sections/<slug:slug>/",
        views.PublicSectionDetailView.as_view(),
        name="public-section-detail",
    ),
    path(
        "public/issues/",
        views.PublicIssueListView.as_view(),
        name="public-issue-list",
    ),
    path(
        "public/issues/current/",
        views.PublicCurrentIssueView.as_view(),
        name="public-current-issue",
    ),
    path(
        "public/issues/<slug:slug>/",
        views.PublicIssueDetailView.as_view(),
        name="public-issue-detail",
    ),
    path(
        "public/articles/",
        views.PublicArticleListView.as_view(),
        name="public-article-list",
    ),
    path(
        "public/articles/<slug:slug>/download/",
        views.PublicArticleDownloadView.as_view(),
        name="public-article-download",
    ),
    path(
        "public/articles/<slug:slug>/export/",
        views.PublicArticleMetadataExportView.as_view(),
        name="public-article-export",
    ),
    path(
        "public/articles/<slug:slug>/",
        views.PublicArticleDetailView.as_view(),
        name="public-article-detail",
    ),
]
