# Generated by Django 5.0.6 on 2026-06-30 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0002_section_last_clustered_at'),
        ('submissions', '0005_submissiontopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=550, unique=True)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='published/articles/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retracted', 'Retracted')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_articles', to='journals.section')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_article', to='submissions.submission')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('published_at'), descending=True, nulls_last=True), '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='idx_article_status_pub'), models.Index(fields=['section', 'status'], name='idx_article_section_status')],
            },
        ),
    ]
