# Generated by Django 5.0.6 on 2026-06-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedarticle',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='published/articles/'),
        ),
    ]
