# Generated by Django 5.0.6 on 2026-07-03 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_alter_publishedarticle_pdf_file'),
        ('submissions', '0007_submissionversion_decision_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedarticle',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_articles', to='submissions.submissionversion'),
        ),
    ]
