# Generated by Django 5.0.6 on 2026-07-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_journalmetadatasettings_access_policy_and_more'),
        ('publishing', '0004_publishedarticle_first_page_publishedarticle_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedarticle',
            name='publication_issue',
            field=models.ForeignKey(blank=True, help_text='Structured journal issue this article belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='journals.issue'),
        ),
    ]
