# Generated by Django 5.0.6 on 2026-07-21 15:26

from django.db import migrations, models


def replace_null_pdf_file_values(apps, schema_editor):
    PublishedArticle = apps.get_model(
        "publishing",
        "PublishedArticle",
    )

    PublishedArticle.objects.filter(
        pdf_file__isnull=True,
    ).update(
        pdf_file="",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0006_backfill_publication_issues'),
    ]

    operations = [
        migrations.RunPython(
            replace_null_pdf_file_values,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='pdf_file',
            field=models.CharField(blank=True, default='', help_text='Private MinIO object key for the published PDF.', max_length=500),
        ),
    ]
