# Generated by Django 5.0.6 on 2026-05-29 16:47

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('issn', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='ISSN must be in the format XXXX-XXXX (e.g. 1234-5678).', regex='^\\d{4}-\\d{4}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sections do not accept new submissions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
