# Generated by Django 5.0.6 on 2026-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='last_clustered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful BERTopic clustering run for this section.', null=True),
        ),
    ]
