# Generated by Django 5.0.6 on 2026-07-05 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_section_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalMetadataSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('journal_title', models.CharField(default='Untitled Journal', max_length=255)),
                ('publisher_name', models.CharField(blank=True, default='', max_length=255)),
                ('print_issn', models.CharField(blank=True, default='', max_length=9, validators=[django.core.validators.RegexValidator(message='ISSN must be in the format XXXX-XXXX (e.g. 1234-5678).', regex='^\\d{4}-\\d{4}$')])),
                ('online_issn', models.CharField(blank=True, default='', max_length=9, validators=[django.core.validators.RegexValidator(message='ISSN must be in the format XXXX-XXXX (e.g. 1234-5678).', regex='^\\d{4}-\\d{4}$')])),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('default_license_name', models.CharField(blank=True, default='', max_length=255)),
                ('default_license_url', models.URLField(blank=True, default='', max_length=500)),
                ('oai_repository_name', models.CharField(blank=True, default='', max_length=255)),
                ('oai_admin_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal metadata settings',
                'verbose_name_plural': 'Journal metadata settings',
            },
        ),
    ]
