# Generated by Django 5.0.6 on 2026-07-09 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_journalmetadatasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='access_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='peer_review_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='publication_frequency',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, help_text='Stable public URL slug for this section.', max_length=280, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Stable public URL slug for this issue.', max_length=280, unique=True)),
                ('volume', models.CharField(blank=True, default='', max_length=50)),
                ('number', models.CharField(blank=True, default='', help_text='Issue number within the volume.', max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Marks the currently featured public issue.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('published_at'), descending=True, nulls_last=True), '-year', 'volume', 'number'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='idx_issue_status_pub'), models.Index(fields=['slug'], name='idx_issue_slug')],
            },
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('volume', 'number', 'year'), name='unique_issue_volume_number_year'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_issue'),
        ),
    ]
