# Generated by Django 5.0.6 on 2026-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_backfill_section_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(help_text='Stable public URL slug for this section.', max_length=280, unique=True),
        ),
    ]
