# Generated by Django 5.0.6 on 2026-07-11 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_require_section_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEditorMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_editor_memberships_created', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_editor_memberships', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editor_memberships', to='journals.section')),
            ],
            options={
                'ordering': ['section__name', 'editor__username'],
                'indexes': [models.Index(fields=['section', 'is_active'], name='idx_section_editor_active'), models.Index(fields=['editor', 'is_active'], name='idx_editor_section_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='sectioneditormembership',
            constraint=models.UniqueConstraint(fields=('section', 'editor'), name='unique_section_editor_membership'),
        ),
    ]
