# Generated by Django 5.0.6 on 2026-07-19 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_sectioneditormembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Journal logo displayed on the public portal.', null=True, upload_to='journal/branding/'),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='primary_color',
            field=models.CharField(default='#0F172A', help_text='Primary journal color in #RRGGBB format.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hexadecimal color in #RRGGBB format.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='priority_action_urgency_weight',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='priority_overdue_work_weight',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='priority_reviewer_shortage_weight',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='priority_revision_round_weight',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='priority_waiting_age_cap_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Waiting age reaches its maximum ranking contribution after this many days.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AddField(
            model_name='journalmetadatasettings',
            name='priority_waiting_age_weight',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='journalmetadatasettings',
            constraint=models.CheckConstraint(check=models.Q(('priority_waiting_age_weight__gt', 0), ('priority_action_urgency_weight__gt', 0), ('priority_reviewer_shortage_weight__gt', 0), ('priority_overdue_work_weight__gt', 0), ('priority_revision_round_weight__gt', 0), _connector='OR'), name='priority_weights_not_all_zero'),
        ),
    ]
