# Generated by Django 5.0.6 on 2026-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_journalmetadatasettings_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('about', 'About the Journal'), ('author-guidelines', 'Author Guidelines'), ('publication-ethics', 'Publication Ethics'), ('open-access', 'Open Access')], max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.CharField(blank=True, default='', help_text='Short introduction displayed below the page title.', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Plain text content. Lines beginning with #, ##, or ### are displayed as section headings.')),
                ('is_published', models.BooleanField(default=False, help_text='Only published pages are visible on the public portal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal content page',
                'verbose_name_plural': 'Journal content pages',
                'ordering': ['slug'],
            },
        ),
    ]
