# Generated by Django 5.0.6 on 2026-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_journalcontentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcontentpage',
            name='slug',
            field=models.SlugField(choices=[('about', 'About the Journal'), ('author-guidelines', 'Author Guidelines'), ('publication-ethics', 'Publication Ethics'), ('open-access', 'Open Access'), ('editorial-board', 'Editorial Board'), ('contact', 'Contact')], max_length=80, unique=True),
        ),
    ]
