# Generated by Django 5.0.6 on 2026-05-29 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('REVIEWER', 'Reviewer'), ('SECTION_MANAGER', 'Section Manager'), ('SECTION_EDITOR', 'Section Editor'), ('EDITOR_IN_CHIEF', 'Editor in Chief'), ('ADMIN', 'Admin'), ('READER', 'Reader')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_received', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='submissions.submission')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission'], name='idx_assignment_submission'), models.Index(fields=['assigned_to'], name='idx_assignment_assigned_to')],
            },
        ),
    ]
