# Generated by Django 5.0.6 on 2026-06-09 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_add_versioning_and_editor_assignment'),
        ('workflow', '0002_reviewerassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviewerassignment',
            name='workflow_re_submiss_4cc94b_idx',
        ),
        migrations.RemoveField(
            model_name='reviewerassignment',
            name='submission',
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='carried_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carried_forward', to='workflow.reviewerassignment'),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reviewer_assignments', to='submissions.submissionversion'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='reviewerassignment',
            index=models.Index(fields=['version'], name='workflow_re_version_5451d0_idx'),
        ),
    ]
