# Generated by Django 5.0.6 on 2026-07-01 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submission_assigned_editor'),
        ('workflow', '0003_reviewer_assignment_version_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviewerassignment',
            name='workflow_re_reviewe_cb4176_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewerassignment',
            name='workflow_re_version_5451d0_idx',
        ),
        migrations.AlterField(
            model_name='reviewerassignment',
            name='response_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewerassignment',
            name='review_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewerassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reviewerassignment',
            index=models.Index(fields=['version', 'status'], name='workflow_re_version_5b6a59_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewerassignment',
            index=models.Index(fields=['reviewer', 'status'], name='workflow_re_reviewe_404a34_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewerassignment',
            index=models.Index(fields=['assigned_by'], name='workflow_re_assigne_2eb128_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewerassignment',
            constraint=models.UniqueConstraint(fields=('version', 'reviewer'), name='unique_reviewer_assignment_per_version'),
        ),
    ]
