# Generated by Django 5.0.6 on 2026-07-13 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_alter_submission_language'),
        ('workflow', '0004_remove_reviewerassignment_workflow_re_reviewe_cb4176_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checklist_version', models.PositiveSmallIntegerField(default=1)),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('PROCEED', 'Proceed to editor assignment'), ('DESK_REJECTED', 'Desk rejected')], default='', max_length=30)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.CharField(blank=True, choices=[('OUT_OF_SCOPE', 'Outside journal or section scope'), ('INCOMPLETE', 'Incomplete submission'), ('QUALITY', 'Insufficient submission quality'), ('GUIDELINES', 'Submission guidelines not followed'), ('ETHICS', 'Ethics or research-integrity concern'), ('OTHER', 'Other')], default='', max_length=30)),
                ('author_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triage_assessments_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_assessments_created', to=settings.AUTH_USER_MODEL)),
                ('submission_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='triage_assessment', to='submissions.submissionversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_triage_status_created')],
            },
        ),
    ]
