# Generated by Django 5.0.6 on 2026-07-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_triageassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionassignment',
            name='assignment_reason',
            field=models.CharField(choices=[('INITIAL', 'Initial assignment'), ('WORKLOAD', 'Workload'), ('CONFLICT', 'Conflict of interest'), ('INACTIVITY', 'Editor inactivity'), ('UNAVAILABLE', 'Editor unavailable'), ('ADMINISTRATIVE', 'Administrative correction')], default='INITIAL', max_length=30),
        ),
    ]
