# Generated by Django 5.0.6 on 2026-07-16 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_add_assignment_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerassignment',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewer_assignments_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='replaces',
            field=models.OneToOneField(blank=True, help_text='The cancelled reviewer assignment replaced by this invitation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='workflow.reviewerassignment'),
        ),
        migrations.AlterField(
            model_name='reviewerassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
