# Generated by Django 5.0.6 on 2026-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_reviewerassignment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerassignment',
            name='review_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the one-time review deadline reminder was successfully sent.', null=True),
        ),
    ]
