# Generated by Django 5.0.6 on 2026-06-16 13:56

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('biography', models.TextField(blank=True, default='')),
                ('expertise_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('publications', models.JSONField(default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_synced_at'],
            },
        ),
    ]
