# Generated by Django 5.0.6 on 2026-07-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reviewerprofile'),
        ('journals', '0008_sectioneditormembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerprofile',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Journal sections in which this reviewer is approved to review manuscripts.', related_name='reviewer_profiles', to='journals.section'),
        ),
    ]
