# Generated by Django 5.0.6 on 2026-07-21 08:42

from django.db import migrations


def copy_status_to_is_active(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    User.objects.filter(
        status__iexact="inactive"
    ).update(is_active=False)

    User.objects.exclude(
        status__iexact="inactive"
    ).update(is_active=True)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_reviewerprofile_sections'),
    ]

    operations = [
        migrations.RunPython(
            copy_status_to_is_active,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
    ]