# Generated by Django 5.0.6 on 2026-05-29 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('es', 'Spanish'), ('ar', 'Arabic'), ('fr', 'French'), ('bn', 'Bengali'), ('pt', 'Portuguese'), ('id', 'Indonesian'), ('ur', 'Urdu'), ('ru', 'Russian'), ('de', 'German'), ('ja', 'Japanese'), ('mr', 'Marathi'), ('vi', 'Vietnamese'), ('te', 'Telugu'), ('sw', 'Swahili'), ('ha', 'Hausa'), ('tr', 'Turkish'), ('tl', 'Tagalog'), ('ta', 'Tamil'), ('ko', 'Korean'), ('am', 'Amharic'), ('th', 'Thai'), ('jv', 'Javanese'), ('it', 'Italian'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('yo', 'Yoruba'), ('aa', 'Afar'), ('ab', 'Abkhazian'), ('ae', 'Avestan'), ('af', 'Afrikaans'), ('ak', 'Akan'), ('an', 'Aragonese'), ('as', 'Assamese'), ('av', 'Avaric'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('ba', 'Bashkir'), ('be', 'Belarusian'), ('bg', 'Bulgarian'), ('bh', 'Bihari languages'), ('bi', 'Bislama'), ('bm', 'Bambara'), ('bo', 'Tibetan'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ce', 'Chechen'), ('ch', 'Chamorro'), ('co', 'Corsican'), ('cr', 'Cree'), ('cs', 'Czech'), ('cu', 'Church Slavic'), ('cv', 'Chuvash'), ('cy', 'Welsh'), ('da', 'Danish'), ('dv', 'Divehi'), ('dz', 'Dzongkha'), ('ee', 'Ewe'), ('el', 'Greek'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('ff', 'Fulah'), ('fi', 'Finnish'), ('fj', 'Fijian'), ('fo', 'Faroese'), ('fy', 'Western Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('gn', 'Guarani'), ('gv', 'Manx'), ('he', 'Hebrew'), ('ho', 'Hiri Motu'), ('hr', 'Croatian'), ('ht', 'Haitian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('hz', 'Herero'), ('ia', 'Interlingua'), ('ie', 'Interlingue'), ('ig', 'Igbo'), ('ii', 'Sichuan Yi'), ('ik', 'Inupiaq'), ('io', 'Ido'), ('is', 'Icelandic'), ('iu', 'Inuktitut'), ('ka', 'Georgian'), ('kg', 'Kongo'), ('ki', 'Kikuyu'), ('kj', 'Kuanyama'), ('kk', 'Kazakh'), ('kl', 'Kalaallisut'), ('km', 'Central Khmer'), ('kr', 'Kanuri'), ('ks', 'Kashmiri'), ('ku', 'Kurdish'), ('kv', 'Komi'), ('kw', 'Cornish'), ('ky', 'Kirghiz'), ('la', 'Latin'), ('lb', 'Luxembourgish'), ('lg', 'Ganda'), ('li', 'Limburgish'), ('ln', 'Lingala'), ('lo', 'Lao'), ('lt', 'Lithuanian'), ('lu', 'Luba-Katanga'), ('lv', 'Latvian'), ('mg', 'Malagasy'), ('mh', 'Marshallese'), ('mi', 'Maori'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('ms', 'Malay'), ('mt', 'Maltese'), ('my', 'Burmese'), ('na', 'Nauru'), ('nb', 'Norwegian Bokmål'), ('nd', 'North Ndebele'), ('ne', 'Nepali'), ('ng', 'Ndonga'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('no', 'Norwegian'), ('nr', 'South Ndebele'), ('nv', 'Navajo'), ('ny', 'Chichewa'), ('oc', 'Occitan'), ('oj', 'Ojibwe'), ('om', 'Oromo'), ('or', 'Oriya'), ('os', 'Ossetian'), ('pa', 'Panjabi'), ('pi', 'Pali'), ('pl', 'Polish'), ('ps', 'Pushto'), ('qu', 'Quechua'), ('rm', 'Romansh'), ('rn', 'Rundi'), ('ro', 'Romanian'), ('rw', 'Kinyarwanda'), ('sa', 'Sanskrit'), ('sc', 'Sardinian'), ('sd', 'Sindhi'), ('se', 'Northern Sami'), ('sg', 'Sango'), ('sh', 'Serbo-Croatian'), ('si', 'Sinhala'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sm', 'Samoan'), ('sn', 'Shona'), ('so', 'Somali'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('ss', 'Swati'), ('st', 'Sotho, Southern'), ('su', 'Sundanese'), ('sv', 'Swedish'), ('tg', 'Tajik'), ('ti', 'Tigrinya'), ('tk', 'Turkmen'), ('tn', 'Tswana'), ('to', 'Tonga'), ('ts', 'Tsonga'), ('tt', 'Tatar'), ('tw', 'Twi'), ('ty', 'Tahitian'), ('ug', 'Uighur'), ('uk', 'Ukrainian'), ('uz', 'Uzbek'), ('ve', 'Venda'), ('vo', 'Volapük'), ('wa', 'Walloon'), ('wo', 'Wolof'), ('xh', 'Xhosa'), ('za', 'Chuang'), ('zu', 'Zulu')], max_length=10)),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('SUSPENDED', 'Suspended')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='journals.section')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
