# Generated by Django 5.0.6 on 2026-06-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('SUSPENDED', 'Suspended'), ('REVIEWED', 'Reviewed')], default='SUBMITTED', max_length=20),
        ),
    ]
