# Generated by Django 5.0.6 on 2026-06-09 11:09

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        ('submissions', '0002_alter_submission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.CharField(blank=True, max_length=500, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('MAJOR_REVISION', 'Major Revision'), ('MINOR_REVISION', 'Minor Revision')], default='PENDING', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='abstract_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('SUSPENDED', 'Suspended'), ('REVIEWED', 'Reviewed'), ('UNDER_REVISION', 'Under Revision'), ('REVISED', 'Revised')], default='SUBMITTED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_c2b4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['author'], name='submissions_author__272c77_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assigned_editor'], name='submissions_assigne_a7156b_idx'),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='submissions.submission'),
        ),
        migrations.AddIndex(
            model_name='submissionversion',
            index=models.Index(fields=['submission'], name='submissions_submiss_0c2d3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionversion',
            unique_together={('submission', 'version_number')},
        ),
    ]
