# Generated by Django 5.0.6 on 2026-06-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_add_versioning_and_editor_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('SUSPENDED', 'Suspended'), ('REVIEWED', 'Reviewed'), ('UNDER_REVISION', 'Under Revision'), ('REVISED', 'Revised'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
    ]
