# Generated by Django 5.0.6 on 2026-07-01 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submissiontopic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, help_text='Current responsible section editor. Historical assignments are stored in SubmissionAssignment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
