# Generated by Django 5.0.6 on 2026-07-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submission_assigned_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionversion',
            name='decision_letter',
            field=models.TextField(blank=True),
        ),
    ]
