# Generated by Django 5.0.6 on 2026-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_submissionversion_response_to_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('es', 'Spanish'), ('ar', 'Arabic'), ('fr', 'French'), ('bn', 'Bengali'), ('pt', 'Portuguese'), ('id', 'Indonesian'), ('ur', 'Urdu'), ('ru', 'Russian'), ('de', 'German'), ('ja', 'Japanese')], max_length=10),
        ),
    ]
