# Generated by Django 5.0.6 on 2026-07-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_alter_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionversion',
            name='blinded_file',
            field=models.CharField(blank=True, help_text='Private MinIO object path for the anonymized manuscript.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('fr', 'French')], max_length=10),
        ),
        migrations.AlterField(
            model_name='submissionversion',
            name='file',
            field=models.CharField(blank=True, help_text='Private MinIO object path for the full manuscript.', max_length=500, null=True),
        ),
    ]
