# Generated by Django 5.0.6 on 2026-07-18 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_submissionversion_blinded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Author-supplied scholarly keywords.'),
        ),
        migrations.CreateModel(
            name='SubmissionCoAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('orcid', models.CharField(blank=True, default='', max_length=19)),
                ('affiliation', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthors', to='submissions.submission')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='submissioncoauthor',
            constraint=models.UniqueConstraint(fields=('submission', 'order'), name='unique_submission_coauthor_order'),
        ),
    ]
