# Generated by Django 5.0.6 on 2026-07-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_submission_keywords_submissioncoauthor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('UNDER_REVISION', 'Under Revision'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
    ]
