# Generated by Django 5.0.6 on 2026-06-04 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0002_reviewerassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Accept'), ('MINOR_REVISION', 'Minor Revision'), ('MAJOR_REVISION', 'Major Revision'), ('REJECT', 'Reject')], max_length=20)),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='workflow.reviewerassignment')),
            ],
        ),
    ]
