# Generated by Django 5.0.6 on 2026-07-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('workflow', '0004_remove_reviewerassignment_workflow_re_reviewe_cb4176_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='comments_for_author',
        ),
        migrations.AddField(
            model_name='review',
            name='comments_for_editor',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['recommendation'], name='reviews_rev_recomme_3ab883_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['submitted_at'], name='reviews_rev_submitt_dc56bd_idx'),
        ),
    ]
