# Generated by Django 5.0.6 on 2026-07-31 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0012_alter_submission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(help_text='Comparison-corpus source type used by the pipeline.', max_length=100)),
                ('pipeline_version', models.CharField(help_text='Version or source commit of the plagiarism pipeline.', max_length=128)),
                ('checkpoint_id', models.CharField(help_text='Identity of the verifier checkpoint used.', max_length=255)),
                ('report_schema_version', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Small report summary suitable for queue and triage views.')),
                ('report', models.JSONField(blank=True, default=dict, help_text='Complete versioned plagiarism report and supporting evidence.')),
                ('error_code', models.CharField(blank=True, default='', help_text='Safe application-level error code.', max_length=64)),
                ('error_message', models.TextField(blank=True, default='', help_text='Safe error message. Must not contain credentials, local paths, database errors, or tracebacks.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when the screening reaches COMPLETED or FAILED.', null=True)),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who requested the screening. Null for automatically scheduled screenings or when the user no longer exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_plagiarism_screenings', to=settings.AUTH_USER_MODEL)),
                ('submission_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plagiarism_screenings', to='submissions.submissionversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='integrity_status_created_idx'), models.Index(fields=['submission_version', '-created_at'], name='integrity_version_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='plagiarismscreening',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING'])), fields=('submission_version',), name='unique_active_plagiarism_screening'),
        ),
    ]
